create database hotelmanagementsystem ;
show databases;
use hotelmanagementsystem;
create table login(username varchar(20) , password varchar(20) ) ;
insert into login values('admin' , '12345') ; 
select * from login ; 
create table employee(name varchar(20) ,age varchar(20) ,gender varchar(20) ,job varchar(20) ,salary varchar(20) ,phone varchar(20) ,email varchar(40) , aadhar varchar(20) ) ;
select * from employee ; 
create table room(roomnumber varchar(20) , availability varchar(20) , clean_status varchar(20) , price varchar(20) , bedtype varchar(20) ) ; 
select * from room ; 
create table driver(name varchar(20) ,age varchar(20) ,gender varchar(20) ,company varchar(20) ,carmodel varchar(20) ,available varchar(20) ,location varchar(40)) ;
select * from driver ;
delete from driver where gender="male" ; 
delete from driver ;
DELETE FROM driver WHERE gender = 'male' ;
select * from driver ;
select * from employee ; 
select * from driver ;  
select * from room ; 
create  table customer(document varchar(20),number  varchar(20),name varchar(20),gender varchar(20),country varchar(20),roomnumber varchar(20),checkintime  varchar(80) ,deposit varchar(20));
 select * from customer;
 create table department(department varchar(30), budget varchar(30));
select * from department ;
select * from customer;
describe customer ;
delete from customer;
select * from room  ; 
show tables ;
delete from customer;
delete from department;
delete from driver;
delete from employee;
delete from room;
insert into department values('Front Office','500000');
insert into department values('HouseKeeping','40000');
insert into department values('Food or beverage','540000');
insert into department values('Security','320000');
select * from employee   ; 
select * from room  ; 
select * from driver  ; 
select * from department  ; 
select * from customer  ; 

